ALTER TABLE "Salesman" ADD COLUMN IF NOT EXISTS "minLeadsPerMonth" INTEGER DEFAULT 0;
ALTER TABLE "Salesman" ADD COLUMN IF NOT EXISTS "maxLeadsPerMonth" INTEGER DEFAULT 0;
ALTER TABLE "Salesman" ADD COLUMN IF NOT EXISTS "useIntelligentOverride" BOOLEAN DEFAULT false;
